# Wallpaper
nitrogen --restore &

# DWM Status
dwmbar &

# Notification client
dunst &

# The compositor
picom &

# Startup application
discord &
spotify &
brave &
element-desktop &
kdeconnect-app &
noisetorch -i -t 75 &
pavucontrol &
/home/anurag/.program/wacom.sh -l &
xournalpp &

# see https://unix.stackexchange.com/a/295652/332452
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    dwm >/dev/null 2>&1
done

# Execute dwm
exec dwm

