# Wallpaper
nitrogen --restore &

# DWM Status
dwmbar &

# Notification client
dunst &

# The compositor
picom &

# Fectchcord
# fetchcord -t 15 -m gb --terminal kitty &

# Startup application
discord &
spotify &
brave &

while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    dwm >/dev/null 2>&1
done

# Execute dwm
exec dwm
