require("plugins")
require("general")
require("plug_config/colour")
require("plug_config/treesitter")
require("plug_config/lualine")
require("plug_config/bufferline")
require("plug_config/autosave")
require("plug_config/colorizer")