set nocompatible              " required filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'frazrepo/vim-rainbow'
Plugin 'codota/tabnine-vim'
Plugin 'itchyny/lightline.vim'
Plugin 'vim-python/python-syntax'
Plugin 'ternjs/tern_for_vim', { 'do' : 'npm install' } 
Plugin 'jiangmiao/auto-pairs'
Plugin 'preservim/nerdtree'

call vundle#end()            " required
filetype plugin indent on    " required

colorscheme molokai         " The Theme of vim
" Link to get the theme https://github.com/tomasr/molokai
highlight Comment cterm=bold

" Extra to c++ syntax highlighting
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_experimental_simple_template_highlight = 1
let g:cpp_experimental_template_highlight = 1
let g:cpp_concepts_highlight = 1

let g:rainbow_active = 1    " Enabling rainbow brackets

" Extra to rainbow brackets
let g:rainbow_load_separately = [
    \ [ '*' , [['(', ')'], ['\[', '\]'], ['{', '}']] ],
    \ [ '*.tex' , [['(', ')'], ['\[', '\]']] ],
    \ [ '*.cpp' , [['(', ')'], ['\[', '\]'], ['{', '}']] ],
    \ [ '*.{html,htm}' , [['(', ')'], ['\[', '\]'], ['{', '}'], ['<\a[^>]*>', '</[^>]*>']] ],
    \ ]
let g:rainbow_guifgs = ['RoyalBlue3', 'DarkOrange3', 'DarkOrchid3', 'FireBrick']
let g:rainbow_ctermfgs = ['lightblue', 'lightgreen', 'yellow', 'red', 'magenta']

let g:python_highlight_all = 1  " Enable python syntax highlighting

map <F8> :NERDTreeToggle<CR>

" Close the preview window after work is done in YCM 
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1

set number                  " Enable number line
set tabstop=4 expandtab shiftwidth=4 smarttab   " Setting up the tab width

set laststatus=2
set noshowmode

" Disabling creation of swap files
set directory=/tmp
set nobackup
set noswapfile

set splitbelow
set splitright

" Shortcut for code running and Executing test cases for competitive programming
" Detial readup https://medium.com/@akashrrao/how-i-use-vim-for-competitive-programming-1f0fc96682e0
autocmd FileType cpp nnoremap     <leader>rr    :!g++ -g --std=c++17 % -o %:r && ./%:r<CR>
autocmd FileType cpp nnoremap     <leader>rt    :!for f in *.test; do echo "\nTEST: $f"; ./%:r < $f; done<CR>
autocmd FileType c nnoremap     <leader>rr    :!gcc -g % -o %:r && ./%:r<CR>
autocmd FileType python nnoremap     <leader>rr    :!python %:r.py<CR>
autocmd FileType python nnoremap     <leader>rt    :!for f in *.test; do echo "\nTEST: $f"; python %:r.py < $f; done<CR>


set clipboard=unnamedplus       " For using global clipboard

" map 'd' key for delete instead of cut
nnoremap d "_d
vnoremap d "_d
