set nocompatible 
colorscheme molokai
syntax on
highlight Comment cterm=bold
set encoding=UTF-8

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'vim-scripts/AutoComplPop'
Plugin 'itchyny/lightline.vim'
Plugin 'vim-python/python-syntax'
Plugin 'ternjs/tern_for_vim', { 'do' : 'npm install' }
Plugin 'jiangmiao/auto-pairs'
Plugin 'preservim/nerdtree'
Plugin 'sheerun/vim-polyglot'
Plugin 'godlygeek/tabular'
Plugin 'anurag3301/vimsence'
Plugin 'ryanoasis/vim-devicons'
"Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'
Plugin 'vwxyutarooo/nerdtree-devicons-syntax'
call vundle#end()            " required
filetype plugin indent on    " required

" Extra to c++ syntax highlighting
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_experimental_template_highlight = 1
let g:cpp_concepts_highlight = 1

set number                  " Enable number line
set tabstop=4 expandtab shiftwidth=4 smarttab   " Setting up the tab width

set laststatus=2
set noshowmode

set complete+=kspell
set completeopt=menuone

let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 1
highlight Directory ctermfg=42

let g:python_highlight_all = 1  " Enable python syntax highlighting

map <F7> :NERDTreeToggle<CR>

" Disabling creation of swap files
set directory=/tmp
set nobackup
set noswapfile

set splitbelow
set splitright

" Shortcut for code running and Executing test cases for competitive programming
" Detial readup https://medium.com/@akashrrao/how-i-use-vim-for-competitive-programming-1f0fc96682e0
autocmd FileType cpp nnoremap     <leader>rr    :!g++ -g --std=c++17 % -o %:r && ./%:r<CR>
autocmd FileType cpp nnoremap     <leader>rt    :!for f in *.test; do echo "\nTEST: $f"; ./%:r < $f; done<CR>
autocmd FileType c nnoremap     <leader>rr    :!gcc -g % -o %:r && ./%:r<CR>
autocmd FileType python nnoremap     <leader>rr    :!python %:r.py<CR>
autocmd FileType python nnoremap     <leader>rt    :!for f in *.test; do echo "\nTEST: $f"; python %:r.py < $f; done<CR>

set clipboard=unnamedplus       " For using global clipboard
let &t_ut=''                    " Kitty colour issue fix
