#!/bin/bash

cross=" "
tick=" "

miner_pid="$(pidof t-rex)"

get_miner_info(){
    if [ "$miner_pid" ]; then
        # echo "Miner Running"
        printf "\x06%sMiner\x01\\n" "$tick"
    else
       # echo "Miner not running"
       printf "\x0a%sMiner\x01\\n" "$cross"
    fi
}

get_miner_info
