#!/bin/bash

# Gets temperature of the GPU
# Dependencies: nvidia drivers and nvidia-settings

PREFIX=' '
FIRE=' '

WARNING_LEVEL=80

get_gputemp()
{
	GPU_TEMP="$(nvidia-settings -q gpucoretemp -t | head -n 1)"

	if [ "$GPU_TEMP" -ge $WARNING_LEVEL ]; then
		PREFIX="$FIRE$PREFIX"
	fi

	printf "\x05%s%s°C\x01\\n" "$PREFIX" "$GPU_TEMP"
}

get_gputemp
