#!/bin/bash

# Prints out spotify song
PREFIX_PLAY=' '
PREFIX_PAUSE=' '

player_status="$(playerctl status -p spotify)"

get_song()
{
    artist="$(playerctl metadata artist -p spotify)"
    title="$(playerctl metadata title -p spotify | sed 's/(.*//')"

    if [ "$player_status" = "Playing" ]; then
        printf "\x06%s %s - %s\x01\\n" "$PREFIX_PLAY" "$artist" "$title"
    else
        printf "\x06%s %s - %s\x01\\n" "$PREFIX_PAUSE" "$artist" "$title"
    fi

}

get_song
