#!/bin/bash

# Prints out spotify song
PREFIX_PLAY=' '
PREFIX_PAUSE=' '

player_status="$(playerctl status -p spotify)"

get_song()
{
    artist="$(playerctl metadata artist -p spotify)"
    title="$(playerctl metadata title -p spotify | sed 's/(.*//')"
    album="$(playerctl metadata album -p spotify)"

    # if (( ${#title} > 20 )); then
    #   title="$(echo $title | cut -c 1-20)..."
    # fi

    if [ "$player_status" = "Playing" ]; then
        if [ "$artist" ]; then
          printf "\x08%s %s - %s\x01\\n" "$PREFIX_PLAY" "$artist" "$title"
        else
          printf "\x08%s %s - %s\x01\\n" "$PREFIX_PLAY" "$album" "$title"
        fi
    else
        if [ "$artist" ]; then
          printf "\x08%s %s - %s\x01\\n" "$PREFIX_PAUSE" "$artist" "$title"
        else
          printf "\x08%s %s - %s\x01\\n" "$PREFIX_PAUSE" "$album" "$title"
        fi
    fi

}

get_song
