#!/bin/bash

# Prints out the volume percentage

get_volume(){
    speakers="alsa_output.pci-0000_05_00.1.hdmi-stereo"
    headphone="alsa_output.pci-0000_07_00.4.analog-stereo"

    curr_device="$(pactl get-default-sink)"

    if [ "$curr_device" = $speakers ]
	then
		VOLUME_ON_ICON=''
		VOLUME_MUTED_ICON='婢'
	else
		VOLUME_ON_ICON=''
		VOLUME_MUTED_ICON='ﳌ'
	fi
        active_sink=$(pacmd list-sinks | awk '/* index:/{print $3}')
        curStatus=$(pacmd list-sinks | grep -A 15 "index: $active_sink$" | awk '/muted/{ print $2}')
        volume=$(pacmd list-sinks | grep -A 15 "index: $active_sink$" | grep 'volume:' | grep -E -v 'base volume:' | awk -F : '{print $3}' | grep -o -P '.{0,3}%'| sed s/.$// | tr -d ' ')

        if [ "${curStatus}" = 'yes' ]
        then
            printf "\x09%s %s\x01\\n" "$VOLUME_MUTED_ICON" "MUTE"
        else
            printf "\x09%s %s\x01\\n"  "$VOLUME_ON_ICON" "$volume%"
        fi
}

get_volume
