lastupdatecheck: 0
recentrepos:
- /home/anurag/repo/my-linux-setup
- /home/anurag/repo/pharma-stock
- /home/anurag/repo/my-dwm
- /home/anurag/files
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
